"""empty message

Revision ID: 422500124931
Revises: e47ab1e079c9
Create Date: 2024-02-01 20:39:29.378995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422500124931'
down_revision = 'e47ab1e079c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvc', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('cvc')

    # ### end Alembic commands ###
